- name: updating apt and cache on all remote ubuntu  servers
  apt:
   upgrade: yes
   update_cache: yes

- name: Install Apache on remote ubuntu servers
  apt:
   name: apache2
   state: present
- name: Ensure Apache is running
  service:
   name: apache2   
   state: started
   enabled: yes