- hosts: webservers
  become: true
  tasks:
  - name: installing apache software
    apt:
      name: apache2
      state: present

  - name: start apache2 service
    service:
      name: apache2
      state: started