- hosts: all
  become: true
  vars:
    appname: apache2
    appstatus: yes
    running: absent
    servicestate: stopped
  tasks:
  - name: Update and upgrade apt packages
    apt:
      upgrade: "{{appstatus}}"
      update_cache: "{{appstatus}}"
      
  - name: Removing "{{appname}}" software
    apt:
      name: "{{appname}}"
      state: "{{running}}"

  - name: start apache2 service
    service:
      name: "{{appname}}"
      state: "{{servicestate}}"