- name: Install Apache on the servers
  hosts: all
  tasks:
   - name: Install latest version of Apache
     apt:
      name: apache2
      state: present
     notify:
      - start apache
  handlers:
     - name: start apache
       service:
         name: apache2
         state: restarted